spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: dev_local
  security:
    ignored: -"*.bundle.*"

# Email Services
  mail:
    host: smtp.gmail.com
    port: 587
    username: pidgeontheatres@gmail.com
    password: lotfophdthvpwdpz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true